from node

RUN npm i -g git+https://github.com/a7medkamel/taskmill-sandbox-bootloader.git

RUN npm i -g git+https://github.com/a7medkamel/taskmill-sandbox-lang-nodejs.git

EXPOSE 8080

WORKDIR /usr/local/lib/node_modules/taskmill-sandbox-bootloader/

CMD breadboard_sandbox_bootloader
